apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    name: backend
    app: capstone
spec:
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      name: backend-pods
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: abdallash/capstone
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/capstone"
  replicas: 1
    